spring.application.name=apiGateway

server.port=${PORT:8080}

spring.cloud.gateway.routes[0].id=authService

spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}

spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**